@Consumer_HostAddress = http://localhost:5193

GET {{Consumer_HostAddress}}/orders
Accept: application/json

###

GET {{Consumer_HostAddress}}/shipments
Accept: application/json

###

GET {{Consumer_HostAddress}}/cancellations
Accept: application/json

###
