@Publisher_HostAddress = http://localhost:5015

POST {{Publisher_HostAddress}}/orders
Content-Type: application/json

{
  "customer": "Testando",
  "amount": 42.50
}

###

POST {{Publisher_HostAddress}}/orders/11111111-1111-1111-1111-111111111111/ship
Content-Type: application/json

{
  "trackingCode": "BR123456789"
}

###

POST {{Publisher_HostAddress}}/orders/11111111-1111-1111-1111-111111111111/cancel
Content-Type: application/json

{
  "reason": "cliente desistiu"
}

###
